<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>4D</string>
	<key>fileTypes</key>
	<array>
		<string>4dm</string>
		<string>4qs</string>
	</array>
	<!-- folds -->
	<key>foldingStartMarker</key>
	<string>/\*</string>
	<key>foldingStopMarker</key>
	<string>\*/</string>		  
	<key>patterns</key>
	<array>
		<dict>
		  <key>name</key>
		  <string>comment.block.4d</string>
		  <key>begin</key>
		  <string>/\*</string>
		  <key>beginCaptures</key>
		  <dict>
			<key>0</key>
			<dict>
			  <key>name</key>
			  <string>punctuation.definition.comment.begin.4d</string>
			</dict>
		  </dict>
		  <key>end</key>
		  <string>\*/</string>
		  <key>endCaptures</key>
		  <dict>
			<key>0</key>
			<dict>
			  <key>name</key>
			  <string>punctuation.definition.comment.end.4d</string>
			</dict>
		  </dict>
		  <key>patterns</key>
		  <array/>
		</dict>
		
		
		
		
		
		
		
		<dict>
		  <key>name</key>
		  <string>comment.line.double-slash.4d</string>
		  <key>begin</key>
		  <string>//</string>
		  <key>beginCaptures</key>
		  <dict>
			<key>0</key>
			<dict>
			  <key>name</key>
			  <string>punctuation.definition.comment.4d</string>
			</dict>
		  </dict>
		  <key>end</key>
		  <string>\n</string>
		  <key>patterns</key>
		  <array/>
		</dict>	
		
		<!-- constants -->
		
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$|:)[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[0-9]+[.,][0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[0-9]+[.,][0-9]+[eE]-?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.exponential.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)0[xX][0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[?][0-9]{2}:[0-9]{2}:[0-9]{2}[?]\b</string>
			<key>name</key>
			<string>constant.other.time.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[!][0-9]{2,4}-[0-9]{2}-[0-9]{2}[!]\b</string>
			<key>name</key>
			<string>constant.other.date.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[!][0-9]{2}-[0-9]{2}-[0-9]{2,4}[!]\b</string>
			<key>name</key>
			<string>constant.other.date.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)([\p{Letter}])([\p{Letter} 0-9])+([\p{Letter}])(?=(:K[0-9]+:[0-9]+))\b</string>
			<key>name</key>
			<string>constant.language.4d</string>
		</dict>	
		
		<!-- strings -->
		
		<dict>
			<key>match</key>
			<string>(?&lt;=["])((\\["ntr\\])|[^"])*(?=["])</string>
			<key>name</key>
			<string>string.quoted.double.4d</string>
		</dict>
		
		<!-- variables -->
		
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[$][0-9]+\b</string>
			<key>name</key>
			<string>variable.parameter.numeric.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[$]([\p{Letter}_]+)([\p{Letter}_0-9]*)+\b</string>
			<key>name</key>
			<string>variable.other.local.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)&lt;&gt;([\p{Letter}_]+)([\p{Letter}_0-9]*)+\b</string>
			<key>name</key>
			<string>variable.other.interprocess.4d</string>
		</dict>			
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)([\p{Letter}])([\p{Letter}0-9])*(?=\.|\()\b</string>
			<key>name</key>
			<string>entity.name.function.orda.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)([\p{Letter}])([\p{Letter}0-9])*(?=\.|\()\b</string>
			<key>name</key>
			<string>support.variable.orda.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)([\p{Letter}])([\p{Letter} 0-9])*([\p{Letter}])(?=(:C[0-9]+))\b</string>
			<key>name</key>
			<string>entity.name.function.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)_[oO]_([cC]_)?([\p{Letter} ])+([\p{Letter}])(?=(:C[0-9]+))\b</string>
			<key>name</key>
			<string>entity.name.function.classic.deprecated.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)([cC]_)([\p{Letter}])+(?=(:C[0-9]+))\b</string>
			<key>name</key>
			<string>support.type.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)(super|this|form|null|4d|ds|cs)(?=(:C[0-9]+)?)\b</string>
			<key>name</key>
			<string>variable.language.orda.4d</string>
		</dict>
		
		<!-- keywords -->
					
		<dict>
			<key>match</key>
			<string>\b(?i:try)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:catch)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end try)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)(#DECLARE)\b</string>
			<key>name</key>
			<string>keyword.other.declare.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:alias )([\p{Letter}]+ )([\p{Letter}\.]*)([\p{Letter}]+)\b</string>
			<key>name</key>
			<string>keyword.other.alias.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:local )?(?i:exposed )?(?i:function )([\p{Letter}]+ )?([\p{Letter}]+)\b</string>
			<key>name</key>
			<string>keyword.other.function.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:return)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:break)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:continue)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:end use)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:fin utiliser)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:begin sql)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:debut sql)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end sql)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin sql)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:case of)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:au cas ou)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end case)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de cas)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:if)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:si)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:else)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:sinon)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de si)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:boucle)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de boucle)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:repeat)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:repeter)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:until)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:jusque)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:while)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:tant que)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end while)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin tant que)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:pour chaque)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end for each)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<!-- must come after end for each -->
		<dict>
			<key>match</key>
			<string>\b(?i:end for)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:for each)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<!-- must come after for each -->
		<dict>
			<key>match</key>
			<string>\b(?i:for)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end if)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de chaque)\b</string>
			<key>name</key>
			<string>keyword.control.4d</string>
		</dict>
		
		
		
		<dict>
			<key>match</key>
			<string>\b(?i:class constructor)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:class extends)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>

		<!-- storage -->

		<dict>
			<key>match</key>
			<string>(?&lt;= : )([\p{Letter}])([\p{Letter}0-9]*)\b</string>
			<key>name</key>
			<string>support.type.orda.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:property)\b</string>
			<key>name</key>
			<string>storage.type.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:var)\b</string>
			<key>name</key>
			<string>storage.type.4d</string>
		</dict>	
		
		<!-- keywords -->
			
		<dict>
			<key>match</key>
			<string>\b(?i:use)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:utiliser)\b</string>
			<key>name</key>
			<string>keyword.other.4d</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:error method)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:error line)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>			
		<dict>
			<key>match</key>
			<string>\b(?i:error formula)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:error)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>			
		<dict>
			<key>match</key>
			<string>\b(?i:mousedown)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:mouseproc)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>			
		<dict>
			<key>match</key>
			<string>\b(?i:mouse[xy])\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:keycode)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:modifiers)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:flddelimit)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>					
		<dict>
			<key>match</key>
			<string>\b(?i:recdelimit)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:ok)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:document)\b</string>
			<key>name</key>
			<string>support.variable.classic.4d</string>
		</dict>	
		<dict>
			<key>name</key>
			<string>keyword.operator.4d</string>
			<key>match</key>
			<string>\+=|\-=|\*=|\/=|\~\||&amp;&amp;|&amp;|\|\|||\||&lt;&lt;|&gt;&gt;|&lt;=|&gt;=|&lt;|&gt;|:=|\?\?|\?\+|\?\-|\+|\-|\*|\/|=|#|^|%</string>
		</dict>		
	</array>
	<key>scopeName</key>
	<string>source.4dm</string>
	<key>uuid</key>
	<string>3CE9544E-E2CC-46DE-A20F-6026C7E75E48</string>
</dict>
</plist>
