<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>4D</string>
	<key>fileTypes</key>
	<array>
		<string>4dm</string>
		<string>4qs</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:try)\b</string>
			<key>name</key>
			<string>keyword.control.try</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:catch)\b</string>
			<key>name</key>
			<string>keyword.control.catch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end try)\b</string>
			<key>name</key>
			<string>keyword.control.end_catch</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:local)\b</string>
			<key>name</key>
			<string>keyword.control.local</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:exposed)\b</string>
			<key>name</key>
			<string>keyword.control.exposed</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:function)\b</string>
			<key>name</key>
			<string>keyword.control.function</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:return)\b</string>
			<key>name</key>
			<string>keyword.control.return</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:break)\b</string>
			<key>name</key>
			<string>keyword.control.break</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:continue)\b</string>
			<key>name</key>
			<string>keyword.control.continue</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:use)\b</string>
			<key>name</key>
			<string>keyword.control.use</string>
		</dict>		
		<dict>
			<key>match</key>
			<string>\b(?i:utiliser)\b</string>
			<key>name</key>
			<string>keyword.control.utiliser</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:end use)\b</string>
			<key>name</key>
			<string>keyword.control.end_use</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>\b(?i:fin utiliser)\b</string>
			<key>name</key>
			<string>keyword.control.fin_utiliser</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:begin sql)\b</string>
			<key>name</key>
			<string>keyword.control.begin_sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:debut sql)\b</string>
			<key>name</key>
			<string>keyword.control.debut_sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end sql)\b</string>
			<key>name</key>
			<string>keyword.control.end_sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin sql)\b</string>
			<key>name</key>
			<string>keyword.control.fin_sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:case of)\b</string>
			<key>name</key>
			<string>keyword.control.case_of</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:au cas ou)\b</string>
			<key>name</key>
			<string>keyword.control.au_cas_ou</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end case)\b</string>
			<key>name</key>
			<string>keyword.control.end_case</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de cas)\b</string>
			<key>name</key>
			<string>keyword.control.fin_de_cas</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:if)\b</string>
			<key>name</key>
			<string>keyword.control.if</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:si)\b</string>
			<key>name</key>
			<string>keyword.control.si</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:else)\b</string>
			<key>name</key>
			<string>keyword.control.else</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:sinon)\b</string>
			<key>name</key>
			<string>keyword.control.sinon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de si)\b</string>
			<key>name</key>
			<string>keyword.control.fin_de_si</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:boucle)\b</string>
			<key>name</key>
			<string>keyword.control.boucle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de boucle)\b</string>
			<key>name</key>
			<string>keyword.control.fin_de_boucle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:repeat)\b</string>
			<key>name</key>
			<string>keyword.control.repeat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:repeter)\b</string>
			<key>name</key>
			<string>keyword.control.repeter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:until)\b</string>
			<key>name</key>
			<string>keyword.control.until</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:jusque)\b</string>
			<key>name</key>
			<string>keyword.control.jusque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:while)\b</string>
			<key>name</key>
			<string>keyword.control.while</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:tant que)\b</string>
			<key>name</key>
			<string>keyword.control.tant_que</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end while)\b</string>
			<key>name</key>
			<string>keyword.control.end_while</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin tant que)\b</string>
			<key>name</key>
			<string>keyword.control.fin_tant_que</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:pour chaque)\b</string>
			<key>name</key>
			<string>keyword.control.pour_chaque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end for each)\b</string>
			<key>name</key>
			<string>keyword.control.end_for_each</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end for)\b</string>
			<key>name</key>
			<string>keyword.control.end_for</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:for each)\b</string>
			<key>name</key>
			<string>keyword.control.for_each</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:for)\b</string>
			<key>name</key>
			<string>keyword.control.for</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:end if)\b</string>
			<key>name</key>
			<string>keyword.control.end_if</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:fin de chaque)\b</string>
			<key>name</key>
			<string>keyword.control.fin_de_chaque</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:class constructor)\b</string>
			<key>name</key>
			<string>keyword.control.class_constructor</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:class extends)\b</string>
			<key>name</key>
			<string>keyword.control.class_extends</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:property)\b</string>
			<key>name</key>
			<string>keyword.control.property</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:alias)\b</string>
			<key>name</key>
			<string>keyword.control.alias</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:var)\b</string>
			<key>name</key>
			<string>keyword.control.var</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)(#DECLARE)\b</string>
			<key>name</key>
			<string>keyword.control.declare</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[?][0-9]{2}:[0-9]{2}:[0-9]{2}[?]\b</string>
			<key>name</key>
			<string>constant.time</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[!][0-9]{2,4}-[0-9]{2}-[0-9]{2}[!]\b</string>
			<key>name</key>
			<string>constant.date.yyyymmdd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[!][0-9]{2}-[0-9]{2}-[0-9]{2,4}[!]\b</string>
			<key>name</key>
			<string>constant.date.ddmmyyyy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)0[xX][0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[0-9]+[.,][0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.num</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[0-9]+[.,][0-9]+[eE]-?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.exp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=["])((\\["ntr\\])|[^"])*(?=["])</string>
			<key>name</key>
			<string>constant.string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[$][0-9]+\b</string>
			<key>name</key>
			<string>entity.parameter.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)[$]([\p{Letter}_]+)([\p{Letter}_0-9]*)+\b</string>
			<key>name</key>
			<string>entity.variable.local</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)&lt;&gt;([\p{Letter}_]+)([\p{Letter}_0-9]*)+\b</string>
			<key>name</key>
			<string>entity.variable.interprocess</string>
		</dict>				
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)([\p{Letter}_])([\p{Letter} ])+([\p{Letter}])(:C[0-9]+)\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Get 4D folder(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Dossier 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Load 4D View document(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Charger document 4D View(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Get 4D file(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)Fichier 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)RESTART 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)REDEMARRER 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)QUIT 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>	
		<dict>
			<key>match</key>
			<string>(?&lt;!\w|\$)(?i)QUITTER 4D(:C[0-9]+)?\b</string>
			<key>name</key>
			<string>variable.command.classic</string>
		</dict>			
	</array>
	<key>scopeName</key>
	<string>source.4dm</string>
	<key>uuid</key>
	<string>3CE9544E-E2CC-46DE-A20F-6026C7E75E48</string>
</dict>
</plist>
